import { Property } from "@/types/properties";

const properties: Property[] = [
  {
    id: 1,
    title: "Cozy 3BR in Oak Lawn",
    price: 350000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1850,
    area: "1,850 sqft",
    address: "Middle Badda, Dhaka, Bangladesh",
    description:
      "A beautifully maintained home with open-plan living, modern kitchen, and a private backyard. Ideal for families looking for comfort and convenience.",
    images: ["/property.png", "/banner.png", "/property.png", "/banner.png"],
    propertyType: "Single Family",
    overview:
      "Well-appointed single family home in a quiet neighborhood, close to schools and parks. Open living spaces and a large backyard make this an ideal family home.",
    keyFeatures: [
      "3 Bedrooms",
      "2 Bathrooms",
      "Large Backyard",
      "2-Car Garage",
      "Central heating",
    ],
    features: ["Central heating", "2-car garage", "Large backyard"],
    lat: 41.7617,
    lng: -87.6756,
    yearBuilt: 1998,
    lot: "0.18 Acres",
    status: "For Sale",
    createdAt: "2025-01-05",
    interior:
      "Open plan living with updated kitchen and hardwood floors throughout.",
    exterior: "Private fenced backyard with patio and mature landscaping.",
    financial: {
      taxes: "~$4,200/year",
      hoa: "$350/month (landscaping, security, community pool)",
      lastSold: "2018 ($320,000)",
    },
    contact: {
      name: "Sarah Agent",
      company: "Oak Realty",
      email: "sarah@oakrealty.com",
      phone: "(555) 123-4567",
    },
  },
  {
    id: 2,
    title: "Modern Condo near Downtown",
    price: 275000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    area: "1,100 sqft",
    address: "45 River Rd, Chicago",
    description:
      "Contemporary condo with rooftop access and great city views. Low maintenance living close to transit and amenities.",
    images: ["/property.png", "/property.png"],
    propertyType: "Condo",
    overview:
      "City-side condo with modern finishes and convenient transit access.",
    keyFeatures: ["2 Bedrooms", "2 Bathrooms", "Rooftop Access", "Gym"],
    features: ["Rooftop access", "Gym", "Secure entry"],
    lat: 41.8781,
    lng: -87.6298,
    yearBuilt: 2012,
    lot: "N/A",
    status: "For Sale",
    createdAt: "2025-01-15",
    interior:
      "Open concept living with floor-to-ceiling windows and modern kitchen.",
    exterior: "Secure building with rooftop terrace and city views.",
    financial: {
      taxes: "~$3,100/year",
      hoa: "$250/month",
      lastSold: "2019 ($240,000)",
    },
    contact: {
      name: "Downtown Realty",
      company: "City Brokers",
      email: "info@citybrokers.com",
      phone: "(555) 987-6543",
    },
  },
  {
    id: 3,
    title: "Spacious Family Home",
    price: 520000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2600,
    area: "2,600 sqft",
    address: "78 Park Ave, Suburbia",
    description:
      "Large family home with updated kitchen, finished basement and an expansive garden. Great school district.",
    images: ["/property.png", "/property.png", "/property.png"],
    propertyType: "Family Home",
    overview:
      "Generous living spaces and updated amenities make this home ideal for growing families.",
    keyFeatures: [
      "4 Bedrooms",
      "3 Bathrooms",
      "Finished Basement",
      "Large Lot",
    ],
    features: ["Finished basement", "Updated kitchen", "Close to schools"],
    lat: 41.9,
    lng: -87.7,
    yearBuilt: 2005,
    lot: "0.4 Acres",
    status: "For Sale",
    createdAt: "2025-02-05",
    interior: "Spacious kitchen with island, family room and formal dining.",
    exterior: "Large yard with deck and garden space.",
    financial: {
      taxes: "~$5,800/year",
      hoa: "$0",
      lastSold: "2016 ($430,000)",
    },
    contact: {
      name: "Family Homes Co.",
      company: "Suburb Realty",
      email: "hello@suburbrealty.com",
      phone: "(555) 222-3333",
    },
  },
  {
    id: 4,
    title: "Modern Luxury Villa",
    price: 1649999,
    bedrooms: 5,
    bathrooms: 3,
    sqft: 5000,
    area: "5,000 sqft",
    address: "2715 Ash Dr, San Jose, CA 95125",
    description:
      "A stunning modern villa in prestigious Ash Drive, featuring clean lines, premium finishes, and an open-concept layout. Perfect blend of luxury and comfort with smart home features and resort-style outdoor living.",
    images: [
      "/property.png",
      "/property.png",
      "/property.png",
      "/property.png",
    ],
    lat: 37.3352,
    lng: -121.8811,
    propertyType: "Family Home",
    yearBuilt: 2019,
    lot: "0.5 Acres",
    status: "For Sale",
    createdAt: "2025-02-08",
    overview:
      "A stunning modern villa in prestigious Ash Drive, featuring clean lines, premium finishes, and an open-concept layout.",
    keyFeatures: [
      "5 Bedrooms",
      "3 Baths",
      "Gourmet Kitchen",
      "Smart Home System",
      "Heated floors",
      "3-Car Garage with EV charging",
      "Solar panels",
    ],
    features: [
      "Gourmet Kitchen with quartz counters & wine fridge",
      "Master Suite with spa bathroom & walk-in closet",
      "Smart Home System & heated floors",
      "3-Car Garage with EV charging",
      "Solar panels",
    ],
    interior:
      "Open great room with floor-to-ceiling windows. Chef's kitchen with island seating. Luxurious master suite includes sitting area.",
    exterior:
      "Landscaped yard with saltwater infinity pool, built-in BBQ, fire pit, and seating areas. Fully fenced with mature trees for privacy.",
    financial: {
      taxes: "~$18,500/year",
      hoa: "$350/month",
      lastSold: "2020 ($1,350,000)",
    },
    contact: {
      name: "Michael Farrior",
      company: "Farrior Homes",
      email: "michaelfarrior@farriorthomes.com",
      phone: "(708) 953-1795",
    },
  },
  {
    id: 5,
    title: "Contemporary High-Rise",
    price: 450000,
    bedrooms: 6,
    bathrooms: 3,
    sqft: 1800,
    area: "1,800 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Modern high-rise apartment with stunning city views and premium amenities.",
    images: ["/banner.png"],
    propertyType: "High-Rise Apartment",
    overview: "Contemporary high-rise with premium finishes and city views.",
    keyFeatures: [
      "6 Bedrooms",
      "3 Bathrooms",
      "City View",
      "Concierge Service",
    ],
    features: ["City views", "Concierge", "Fitness center"],
    lat: 41.89,
    lng: -87.62,
    yearBuilt: 2015,
    lot: "N/A",
    status: "For Sale",
    createdAt: "2025-12-01",
    interior: "Modern open concept with floor-to-ceiling windows.",
    exterior: "Balcony with panoramic city views.",
    financial: {
      taxes: "~$6,000/year",
      hoa: "$500/month",
      lastSold: "2021 ($400,000)",
    },
    contact: {
      name: "Urban Living Realty",
      company: "City Homes",
      email: "info@cityhomes.com",
      phone: "(555) 555-5555",
    },
  },
  {
    id: 6,
    title: "Charming Cottage",
    price: 310000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3660,
    area: "3,660 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Charming cottage with character and modern updates in a quiet neighborhood.",
    images: ["/banner.png"],
    propertyType: "Charming Cottage",
    overview: "Character-filled cottage with recent updates.",
    keyFeatures: ["4 Bedrooms", "3 Bathrooms", "Original Features", "Updated"],
    features: ["Hardwood floors", "Character details", "Updated systems"],
    lat: 41.88,
    lng: -87.61,
    yearBuilt: 1985,
    lot: "0.25 Acres",
    status: "For Sale",
    createdAt: "2025-12-03",
    interior: "Charming with period details and modern kitchen.",
    exterior: "Landscaped garden with patio.",
    financial: {
      taxes: "~$4,100/year",
      hoa: "$0",
      lastSold: "2019 ($280,000)",
    },
    contact: {
      name: "Charm Homes LLC",
      company: "Heritage Realty",
      email: "info@heritagerealty.com",
      phone: "(555) 666-6666",
    },
  },
  {
    id: 7,
    title: "Stunning Waterfront",
    price: 850000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 3222,
    area: "3,222 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Spectacular waterfront property with private beach access and luxury finishes.",
    images: ["/banner.png"],
    propertyType: "Waterfront Villa",
    overview: "Waterfront luxury with private beach access.",
    keyFeatures: ["2 Bedrooms", "2 Bathrooms", "Beach Access", "Water View"],
    features: ["Private beach", "Water views", "Luxury finishes"],
    lat: 41.87,
    lng: -87.6,
    yearBuilt: 2018,
    lot: "1.5 Acres",
    status: "For Sale",
    createdAt: "2025-12-05",
    interior: "Luxury finishes with panoramic water views.",
    exterior: "Private beach and waterfront landscape design.",
    financial: {
      taxes: "~$12,000/year",
      hoa: "$400/month",
      lastSold: "2020 ($750,000)",
    },
    contact: {
      name: "Waterfront Estates",
      company: "Luxury Living",
      email: "info@luxuryliving.com",
      phone: "(555) 777-7777",
    },
  },
  {
    id: 8,
    title: "Historic Townhouse",
    price: 380000,
    bedrooms: 6,
    bathrooms: 3,
    sqft: 3542,
    area: "3,542 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Historic townhouse with period charm and modern renovation in prestigious area.",
    images: ["/banner.png"],
    propertyType: "Historic Townhouse",
    overview: "Historic townhouse with modern updates in prime location.",
    keyFeatures: ["6 Bedrooms", "3 Bathrooms", "Historic", "Recently Updated"],
    features: ["Original details", "Modern kitchen", "Roof deck"],
    lat: 41.86,
    lng: -87.59,
    yearBuilt: 1920,
    lot: "0.15 Acres",
    status: "For Sale",
    createdAt: "2025-12-07",
    interior: "Historic charm with updated systems and modern amenities.",
    exterior: "Roof deck with city views.",
    financial: {
      taxes: "~$3,500/year",
      hoa: "$200/month",
      lastSold: "2018 ($350,000)",
    },
    contact: {
      name: "Historic Properties",
      company: "Urban Realty",
      email: "info@urbanrealty.com",
      phone: "(555) 888-8888",
    },
  },
  {
    id: 9,
    title: "Eco-Friendly Home",
    price: 420000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Sustainable eco-friendly home with green features and energy efficiency.",
    images: ["/banner.png"],
    propertyType: "Luxury Villa",
    overview: "Environmentally conscious design with modern efficiency.",
    keyFeatures: [
      "Solar Panels",
      "Energy Efficient",
      "Green Materials",
      "Smart Home",
    ],
    features: ["Solar panels", "High efficiency HVAC", "Sustainable materials"],
    lat: 41.85,
    lng: -87.58,
    yearBuilt: 2020,
    lot: "0.2 Acres",
    status: "For Sale",
    createdAt: "2025-12-09",
    interior: "Modern eco-friendly design with sustainable materials.",
    exterior: "Native plant landscaping.",
    financial: {
      taxes: "~$3,000/year",
      hoa: "$150/month",
      lastSold: "2021 ($400,000)",
    },
    contact: {
      name: "Green Living Homes",
      company: "Sustainable Realty",
      email: "info@sustainablerealty.com",
      phone: "(555) 999-9999",
    },
  },
  {
    id: 10,
    title: "Contemporary High-Rise",
    price: 380000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Contemporary high-rise with modern design and premium amenities.",
    images: ["/banner.png"],
    propertyType: "Luxury Villa",
    overview: "Modern high-rise living at its finest.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Modern", "Premium Location"],
    features: ["Indoor pool", "Gym", "Concierge"],
    lat: 41.84,
    lng: -87.57,
    yearBuilt: 2016,
    lot: "N/A",
    status: "For Sale",
    createdAt: "2025-12-11",
    interior: "Contemporary design with high-end finishes.",
    exterior: "Urban setting with building amenities.",
    financial: {
      taxes: "~$2,500/year",
      hoa: "$600/month",
      lastSold: "2019 ($350,000)",
    },
    contact: {
      name: "Modern Living",
      company: "Contemporary Real Estate",
      email: "info@contemporaryrealty.com",
      phone: "(555) 101-0101",
    },
  },
  {
    id: 11,
    title: "Luxury Penthouse",
    price: 950000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Ultra-luxury penthouse with panoramic views and exclusive amenities.",
    images: ["/banner.png"],
    propertyType: "Luxury Villa",
    overview: "Penthouse living with unparalleled luxury and views.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Penthouse", "Private Elevator"],
    features: ["Private elevator", "Terrace", "Wine cellar"],
    lat: 41.83,
    lng: -87.56,
    yearBuilt: 2017,
    lot: "N/A",
    status: "For Sale",
    createdAt: "2025-12-13",
    interior: "Ultimate luxury with premium materials and views.",
    exterior: "Private rooftop terrace with city views.",
    financial: {
      taxes: "~$15,000/year",
      hoa: "$1000/month",
      lastSold: "2021 ($900,000)",
    },
    contact: {
      name: "Luxury Living",
      company: "Elite Properties",
      email: "info@eliteproperties.com",
      phone: "(555) 202-0202",
    },
  },
  {
    id: 12,
    title: "Country Estate",
    price: 680000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Expansive country estate on scenic grounds with privacy and natural beauty.",
    images: ["/banner.png"],
    propertyType: "Luxury Villa",
    overview: "Serene country living with privacy and natural surroundings.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Acreage", "Privacy"],
    features: ["Acreage", "Private entry", "Landscaped grounds"],
    lat: 41.82,
    lng: -87.55,
    yearBuilt: 2008,
    lot: "5 Acres",
    status: "For Sale",
    createdAt: "2025-12-15",
    interior: "Spacious country home with premium finishes.",
    exterior: "Extensive grounds with natural landscape.",
    financial: {
      taxes: "~$7,000/year",
      hoa: "$0",
      lastSold: "2019 ($600,000)",
    },
    contact: {
      name: "Country Properties",
      company: "Rural Realty",
      email: "info@ruralrealty.com",
      phone: "(555) 303-0303",
    },
  },
  {
    id: 13,
    title: "Beachfront Villa",
    price: 1200000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Exclusive beachfront villa with direct beach access and resort amenities.",
    images: ["/banner.png"],
    propertyType: "Luxury Villa",
    overview: "Beachfront living with resort-style amenities.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Beach Access", "Resort Style"],
    features: ["Private beach", "Pool", "Spa"],
    lat: 41.81,
    lng: -87.54,
    yearBuilt: 2014,
    lot: "1 Acre",
    status: "For Sale",
    createdAt: "2025-12-17",
    interior: "Tropical-inspired luxury design.",
    exterior: "Direct beach access with cabana.",
    financial: {
      taxes: "~$18,000/year",
      hoa: "$800/month",
      lastSold: "2020 ($1,100,000)",
    },
    contact: {
      name: "Beach Homes",
      company: "Coastal Living",
      email: "info@coastalliving.com",
      phone: "(555) 404-0404",
    },
  },
  {
    id: 14,
    title: "Artist Loft",
    price: 320000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Artistic loft in vibrant neighborhood with high ceilings and creative space.",
    images: ["/banner.png"],
    propertyType: "Family Home",
    overview: "Creative spaces in artistic neighborhood.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Loft", "High Ceilings"],
    features: ["High ceilings", "Exposed brick", "Large windows"],
    lat: 41.8,
    lng: -87.53,
    yearBuilt: 1995,
    lot: "N/A",
    status: "For Sale",
    createdAt: "2025-12-19",
    interior: "Open loft concept with creative spaces.",
    exterior: "Historic building in arts district.",
    financial: {
      taxes: "~$2,800/year",
      hoa: "$250/month",
      lastSold: "2018 ($280,000)",
    },
    contact: {
      name: "Arts District Realty",
      company: "Creative Living",
      email: "info@creativeliving.com",
      phone: "(555) 505-0505",
    },
  },
  {
    id: 15,
    title: "Mountain Retreat",
    price: 580000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Peaceful mountain retreat with scenic views and outdoor recreation access.",
    images: ["/banner.png"],
    propertyType: "Single Family",
    overview: "Mountain serenity with outdoor adventure access.",
    keyFeatures: [
      "1 Bedroom",
      "3 Bathrooms",
      "Mountain Views",
      "Trails Access",
    ],
    features: ["Mountain views", "Deck", "Trail access"],
    lat: 41.79,
    lng: -87.52,
    yearBuilt: 2010,
    lot: "2 Acres",
    status: "For Sale",
    createdAt: "2025-12-21",
    interior: "Rustic luxury with modern amenities.",
    exterior: "Expansive deck with mountain vistas.",
    financial: {
      taxes: "~$5,000/year",
      hoa: "$0",
      lastSold: "2019 ($500,000)",
    },
    contact: {
      name: "Mountain Properties",
      company: "Alpine Realty",
      email: "info@alpinerealty.com",
      phone: "(555) 606-0606",
    },
  },
  {
    id: 16,
    title: "Urban Apartment",
    price: 295000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Trendy urban apartment in heart of city with walkable neighborhood.",
    images: ["/banner.png"],
    propertyType: "Duplex",
    overview: "Urban living with walkability and convenience.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Urban", "Walkable"],
    features: ["Near transit", "Local shops", "Restaurants"],
    lat: 41.78,
    lng: -87.51,
    yearBuilt: 2011,
    lot: "N/A",
    status: "For Sale",
    createdAt: "2025-12-23",
    interior: "Modern urban design with efficiency.",
    exterior: "Urban location with building amenities.",
    financial: {
      taxes: "~$3,200/year",
      hoa: "$400/month",
      lastSold: "2020 ($270,000)",
    },
    contact: {
      name: "Urban Living Realty",
      company: "City Center Properties",
      email: "info@citycentreproperties.com",
      phone: "(555) 707-0707",
    },
  },
  {
    id: 17,
    title: "Ranch Property",
    price: 520000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Spacious ranch property with working land and outdoor potential.",
    images: ["/banner.png"],
    propertyType: "Ranch",
    overview: "Ranch-style property with development potential.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Acreage", "Potential"],
    features: ["Large acreage", "Barn", "Storage facilities"],
    lat: 41.77,
    lng: -87.5,
    yearBuilt: 2000,
    lot: "10 Acres",
    status: "For Sale",
    createdAt: "2025-12-25",
    interior: "Rustic ranch home with character.",
    exterior: "Extensive working land with facilities.",
    financial: {
      taxes: "~$4,500/year",
      hoa: "$0",
      lastSold: "2018 ($450,000)",
    },
    contact: {
      name: "Ranch Properties",
      company: "Rural Living Realty",
      email: "info@rurallivingrealty.com",
      phone: "(555) 808-0808",
    },
  },
  {
    id: 18,
    title: "Garden Home",
    price: 385000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Charming garden home with mature landscaping and green spaces.",
    images: ["/banner.png"],
    propertyType: "Single Family",
    overview: "Beautiful garden setting with lush landscaping.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Mature Garden", "Green Space"],
    features: ["Mature trees", "Garden beds", "Seating areas"],
    lat: 41.76,
    lng: -87.49,
    yearBuilt: 2002,
    lot: "0.5 Acres",
    status: "For Sale",
    createdAt: "2025-12-27",
    interior: "Charming home with garden views throughout.",
    exterior: "Professionally landscaped with mature plantings.",
    financial: {
      taxes: "~$3,600/year",
      hoa: "$0",
      lastSold: "2019 ($360,000)",
    },
    contact: {
      name: "Garden Homes",
      company: "Landscape Living Realty",
      email: "info@landscapelivingrealty.com",
      phone: "(555) 909-0909",
    },
  },
  {
    id: 19,
    title: "Family Compound",
    price: 760000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Multi-unit family compound with recreational facilities and privacy.",
    images: ["/banner.png"],
    propertyType: "Family Home",
    overview: "Family compound with multiple living spaces.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Multi-Unit", "Recreational"],
    features: ["Guest house", "Pool", "Tennis court"],
    lat: 41.75,
    lng: -87.48,
    yearBuilt: 2006,
    lot: "3 Acres",
    status: "For Sale",
    createdAt: "2025-12-29",
    interior: "Multiple living areas with premium finishes.",
    exterior: "Recreational facilities and manicured grounds.",
    financial: {
      taxes: "~$8,500/year",
      hoa: "$0",
      lastSold: "2020 ($700,000)",
    },
    contact: {
      name: "Family Properties",
      company: "Compound Realty",
      email: "info@compoundrealty.com",
      phone: "(555) 101-1010",
    },
  },
  {
    id: 20,
    title: "Contemporary High-Rise",
    price: 410000,
    bedrooms: 1,
    bathrooms: 3,
    sqft: 1326,
    area: "1,326 sqft",
    address: "100 Skyline Dr. Chicago, 60614",
    description:
      "Modern high-rise apartment with premium finishes and city convenience.",
    images: ["/banner.png"],
    propertyType: "High-Rise Apartment",
    overview: "Contemporary high-rise living.",
    keyFeatures: ["1 Bedroom", "3 Bathrooms", "Modern", "Premium"],
    features: ["City views", "Concierge", "Fitness center"],
    lat: 41.74,
    lng: -87.47,
    yearBuilt: 2014,
    lot: "N/A",
    status: "For Sale",
    createdAt: "2026-02-15",
    interior: "Contemporary design with modern finishes.",
    exterior: "Urban location with building amenities.",
    financial: {
      taxes: "~$4,100/year",
      hoa: "$550/month",
      lastSold: "2021 ($380,000)",
    },
    contact: {
      name: "Modern Living",
      company: "Contemporary Properties",
      email: "info@contemporaryproperties.com",
      phone: "(555) 111-1111",
    },
  },
];

export function getAllProperties() {
  return properties;
}

export function getPropertyById(id: number) {
  return properties.find((p) => p.id === id) ?? null;
}

export default properties;
